from time import sleep
from random import choice,randrange
import os

nums = [1,0]
size=30
while True:
    print  
    (randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,
    randrange(1,5)* " ",choice(nums) ,)
    sleep(0.1)